/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ClientDetail service. Represents a row in the &quot;ClientDetail_ClientDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adj.model.impl.ClientDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adj.model.impl.ClientDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClientDetail
 * @generated
 */
@ProviderType
public interface ClientDetailModel
	extends BaseModel<ClientDetail>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a client detail model instance should use the {@link ClientDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this client detail.
	 *
	 * @return the primary key of this client detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this client detail.
	 *
	 * @param primaryKey the primary key of this client detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this client detail.
	 *
	 * @return the uuid of this client detail
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this client detail.
	 *
	 * @param uuid the uuid of this client detail
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the client ID of this client detail.
	 *
	 * @return the client ID of this client detail
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this client detail.
	 *
	 * @param clientId the client ID of this client detail
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the group ID of this client detail.
	 *
	 * @return the group ID of this client detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this client detail.
	 *
	 * @param groupId the group ID of this client detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this client detail.
	 *
	 * @return the company ID of this client detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this client detail.
	 *
	 * @param companyId the company ID of this client detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this client detail.
	 *
	 * @return the user ID of this client detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this client detail.
	 *
	 * @param userId the user ID of this client detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this client detail.
	 *
	 * @return the user uuid of this client detail
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this client detail.
	 *
	 * @param userUuid the user uuid of this client detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this client detail.
	 *
	 * @return the user name of this client detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this client detail.
	 *
	 * @param userName the user name of this client detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this client detail.
	 *
	 * @return the create date of this client detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this client detail.
	 *
	 * @param createDate the create date of this client detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this client detail.
	 *
	 * @return the modified date of this client detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this client detail.
	 *
	 * @param modifiedDate the modified date of this client detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this client detail.
	 *
	 * @return the name of this client detail
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this client detail.
	 *
	 * @param name the name of this client detail
	 */
	public void setName(String name);

	/**
	 * Returns the email of this client detail.
	 *
	 * @return the email of this client detail
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this client detail.
	 *
	 * @param email the email of this client detail
	 */
	public void setEmail(String email);

	/**
	 * Returns the confirm email of this client detail.
	 *
	 * @return the confirm email of this client detail
	 */
	@AutoEscape
	public String getConfirmEmail();

	/**
	 * Sets the confirm email of this client detail.
	 *
	 * @param confirmEmail the confirm email of this client detail
	 */
	public void setConfirmEmail(String confirmEmail);

	/**
	 * Returns the age of this client detail.
	 *
	 * @return the age of this client detail
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this client detail.
	 *
	 * @param age the age of this client detail
	 */
	public void setAge(String age);

	/**
	 * Returns the phone no of this client detail.
	 *
	 * @return the phone no of this client detail
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this client detail.
	 *
	 * @param phoneNo the phone no of this client detail
	 */
	public void setPhoneNo(String phoneNo);

	/**
	 * Returns the aadhar card of this client detail.
	 *
	 * @return the aadhar card of this client detail
	 */
	@AutoEscape
	public String getAadharCard();

	/**
	 * Sets the aadhar card of this client detail.
	 *
	 * @param aadharCard the aadhar card of this client detail
	 */
	public void setAadharCard(String aadharCard);

}